### ISSUE TITLE
Panic when polling device on dx11

### ISSUE THREAD

**Issue by Dinnerbone** [gfx-rs/wgpu#1009]
**Description**
When polling the device with dx11 backend, the application will panic with a failed assertion.

I couldn't get this to reproduce with the `capture` wgpu-rs sample, so I suspect it may only happen on the 2nd poll?

**Repro steps**
You can reproduce it with our project:
- Clone [ruffle](https://github.com/ruffle-rs/ruffle/)
- Download [this collection of swfs](https://github.com/gfx-rs/wgpu/files/5381371/newgrounds_sample.zip) and extract it somewhere
- Run: `cargo run --package exporter -- ./newgrounds_sample ./out -g dx11`

**Expected vs observed behavior**
I expect hugs, not bugs!

**Extra materials**
Panic:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `-2005270523`,
 right: `0`', C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx11-0.6.10\src\lib.rs:2934:13
stack backtrace:
   0:     0x7ff7f665d7d9 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff7f665d7d9 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7f665d7d9 - std::sys_common::backtrace::_print_fmt
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:79
   3:     0x7ff7f665d7d9 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:58
   4:     0x7ff7f6676c2b - core::fmt::write
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\fmt\mod.rs:1082
   5:     0x7ff7f66590b4 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\io\mod.rs:1514
   6:     0x7ff7f666087b - std::sys_common::backtrace::_print
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:61
   7:     0x7ff7f666087b - std::sys_common::backtrace::print
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:48
   8:     0x7ff7f666087b - std::panicking::default_hook::{{closure}}
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:200
   9:     0x7ff7f66604b9 - std::panicking::default_hook
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:219
  10:     0x7ff7f666105f - std::panicking::rust_panic_with_hook
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:569
  11:     0x7ff7f6660bc5 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:476
  12:     0x7ff7f665e08f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:153
  13:     0x7ff7f6660b79 - std::panicking::begin_panic_handler
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:475
  14:     0x7ff7f6660b2c - std::panicking::begin_panic_fmt
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:429
  15:     0x7ff7f59d6e5e - gfx_backend_dx11::MemoryInvalidate::map
                               at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx11-0.6.10\src\lib.rs:2934
  16:     0x7ff7f59d65cd - gfx_backend_dx11::MemoryInvalidate::download
                               at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx11-0.6.10\src\lib.rs:2895
  17:     0x7ff7f59d68be - gfx_backend_dx11::MemoryInvalidate::do_invalidate
                               at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx11-0.6.10\src\lib.rs:2913
  18:     0x7ff7f59d7851 - gfx_backend_dx11::Memory::invalidate
                               at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx11-0.6.10\src\lib.rs:3046
  19:     0x7ff7f5147279 - gfx_backend_dx11::device::{{impl}}::invalidate_mapped_memory_ranges<core::iter::sources::Once<tuple<gfx_backend_dx11::Memory*, gfx_hal::memory::Segment>>>
                               at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx11-0.6.10\src\device.rs:2133
  20:     0x7ff7f554173a - wgpu_core::device::map_buffer<gfx_backend_dx11::Backend>
                               at C:\Users\dinne\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\7ac706f\wgpu-core\src\device\mod.rs:187
  21:     0x7ff7f535ea3a - wgpu_core::device::life::LifetimeTracker<gfx_backend_dx11::Backend>::handle_mapping<gfx_backend_dx11::Backend,wgpu_core::hub::IdentityManagerFactory>
                               at C:\Users\dinne\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\7ac706f\wgpu-core\src\device\life.rs:731
  22:     0x7ff7f55573a7 - wgpu_core::device::Device<gfx_backend_dx11::Backend>::maintain<gfx_backend_dx11::Backend,wgpu_core::hub::IdentityManagerFactory>
                               at C:\Users\dinne\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\7ac706f\wgpu-core\src\device\mod.rs:362
  23:     0x7ff7f540e6f6 - wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_poll<wgpu_core::hub::IdentityManagerFactory,gfx_backend_dx11::Backend>
                               at C:\Users\dinne\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\7ac706f\wgpu-core\src\device\mod.rs:3633
  24:     0x7ff7f52c6bd6 - wgpu::backend::direct::{{impl}}::device_poll
                               at C:\Users\dinne\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\e3eadca\src\backend\direct.rs:1053
  25:     0x7ff7f5273ee5 - wgpu::Device::poll
                               at C:\Users\dinne\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\e3eadca\src\lib.rs:1423
  26:     0x7ff7f507e347 - ruffle_render_wgpu::target::TextureTarget::capture
                               at W:\personal\ruffle\render\wgpu\src\target.rs:160
  27:     0x7ff7f502f78c - exporter::take_screenshot
                               at W:\personal\ruffle\exporter\src\main.rs:142
  28:     0x7ff7f50317d3 - exporter::capture_multiple_swfs
                               at W:\personal\ruffle\exporter\src\main.rs:292
  29:     0x7ff7f5033031 - exporter::main
                               at W:\personal\ruffle\exporter\src\main.rs:396
  30:     0x7ff7f506039b - core::ops::function::FnOnce::call_once<fn() -> core::result::Result<tuple<>, alloc::boxed::Box<Error>>,tuple<>>
                               at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  31:     0x7ff7f504513e - std::sys_common::backtrace::__rust_begin_short_backtrace<fn() -> core::result::Result<tuple<>, alloc::boxed::Box<Error>>,core::result::Result<tuple<>, alloc::boxed::Box<Error>>>
                               at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys_common\backtrace.rs:137
  32:     0x7ff7f5037921 - std::rt::lang_start::{{closure}}<core::result::Result<tuple<>, alloc::boxed::Box<Error>>>
                               at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:66
  33:     0x7ff7f6661376 - core::ops::function::impls::{{impl}}::call_once
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\library\core\src\ops\function.rs:280
  34:     0x7ff7f6661376 - std::panicking::try::do_call
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:373
  35:     0x7ff7f6661376 - std::panicking::try
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:337
  36:     0x7ff7f6661376 - std::panic::catch_unwind
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panic.rs:379
  37:     0x7ff7f6661376 - std::rt::lang_start_internal
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\rt.rs:51
  38:     0x7ff7f50378f3 - std::rt::lang_start<core::result::Result<tuple<>, alloc::boxed::Box<Error>>>
                               at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:65
  39:     0x7ff7f5034160 - main
  40:     0x7ff7f68d46d4 - invoke_main
                               at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  41:     0x7ff7f68d46d4 - __scrt_common_main_seh
                               at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  42:     0x7ff9b32f7034 - BaseThreadInitThunk
  43:     0x7ff9b39bcec1 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\exporter.exe W:\personal\ruffle-visual-tests out -g dx11` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Platform**
Windows 10 x64
DirectX 11 backend only

**Comment by cwfitzgerald** [comment]
Fixed in gfx-backend-dx11 0.6.11

**Comment by Dinnerbone** [comment]
Still exists in 0.6.11 but not as common. I can trigger it with the same input but it doesn't seem deterministic - can happen on the first `poll()` or much later.

To reproduce now:
- Clone [ruffle](https://github.com/ruffle-rs/ruffle/)
- `cargo update` to ensure dx11 is at 0.6.11 (we've not pulled it to master yet)
- Download [this other collection of swfs](https://github.com/gfx-rs/wgpu/files/5452279/196000.zip) and extract it somewhere
- Run: `cargo run --package exporter -- ./196000 ./out -g dx11`

Panic:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `-2005270523`,
 right: `0`', C:\Users\dinne\.cargo\git\checkouts\gfx-3bb32718e62372ef\acfc78f\src\backend\dx11\src\lib.rs:3064:13
stack backtrace:
   0:     0x7ff725b21c39 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff725b21c39 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff725b21c39 - std::sys_common::backtrace::_print_fmt
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:79
   3:     0x7ff725b21c39 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:58
   4:     0x7ff725b3b08b - core::fmt::write
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\fmt\mod.rs:1082
   5:     0x7ff725b1d514 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\io\mod.rs:1514
   6:     0x7ff725b24cdb - std::sys_common::backtrace::_print
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:61
   7:     0x7ff725b24cdb - std::sys_common::backtrace::print
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:48
   8:     0x7ff725b24cdb - std::panicking::default_hook::{{closure}}
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:200
   9:     0x7ff725b24919 - std::panicking::default_hook
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:219
  10:     0x7ff725b254bf - std::panicking::rust_panic_with_hook
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:569
  11:     0x7ff725b25025 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:476
  12:     0x7ff725b224ef - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:153
  13:     0x7ff725b24fd9 - std::panicking::begin_panic_handler
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:475
  14:     0x7ff725b24f8c - std::panicking::begin_panic_fmt
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:429
  15:     0x7ff724e8564e - gfx_backend_dx11::MemoryInvalidate::map
                               at C:\Users\dinne\.cargo\git\checkouts\gfx-3bb32718e62372ef\acfc78f\src\backend\dx11\src\lib.rs:3064
  16:     0x7ff724e84b52 - gfx_backend_dx11::MemoryInvalidate::download
                               at C:\Users\dinne\.cargo\git\checkouts\gfx-3bb32718e62372ef\acfc78f\src\backend\dx11\src\lib.rs:3019
  17:     0x7ff724e84f60 - gfx_backend_dx11::MemoryInvalidate::do_invalidate
                               at C:\Users\dinne\.cargo\git\checkouts\gfx-3bb32718e62372ef\acfc78f\src\backend\dx11\src\lib.rs:3038
  18:     0x7ff724e860ed - gfx_backend_dx11::Memory::invalidate
                               at C:\Users\dinne\.cargo\git\checkouts\gfx-3bb32718e62372ef\acfc78f\src\backend\dx11\src\lib.rs:3181
  19:     0x7ff7247c9039 - gfx_backend_dx11::device::{{impl}}::invalidate_mapped_memory_ranges<core::iter::sources::Once<tuple<gfx_backend_dx11::Memory*, gfx_hal::memory::Segment>>>
                               at C:\Users\dinne\.cargo\git\checkouts\gfx-3bb32718e62372ef\acfc78f\src\backend\dx11\src\device.rs:2165
  20:     0x7ff7249818ca - wgpu_core::device::map_buffer<gfx_backend_dx11::Backend>
                               at C:\Users\dinne\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\7ac706f\wgpu-core\src\device\mod.rs:187
  21:     0x7ff72456670a - wgpu_core::device::life::LifetimeTracker<gfx_backend_dx11::Backend>::handle_mapping<gfx_backend_dx11::Backend,wgpu_core::hub::IdentityManagerFactory>
                               at C:\Users\dinne\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\7ac706f\wgpu-core\src\device\life.rs:731
  22:     0x7ff7249981f7 - wgpu_core::device::Device<gfx_backend_dx11::Backend>::maintain<gfx_backend_dx11::Backend,wgpu_core::hub::IdentityManagerFactory>
                               at C:\Users\dinne\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\7ac706f\wgpu-core\src\device\mod.rs:362
  23:     0x7ff7248cf556 - wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_poll<wgpu_core::hub::IdentityManagerFactory,gfx_backend_dx11::Backend>
                               at C:\Users\dinne\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\7ac706f\wgpu-core\src\device\mod.rs:3633
  24:     0x7ff724645ed6 - wgpu::backend::direct::{{impl}}::device_poll
                               at C:\Users\dinne\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\e3eadca\src\backend\direct.rs:1053
  25:     0x7ff7247c10a5 - wgpu::Device::poll
                               at C:\Users\dinne\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\e3eadca\src\lib.rs:1423
  26:     0x7ff72453cfc7 - ruffle_render_wgpu::target::TextureTarget::capture
                               at W:\personal\ruffle\render\wgpu\src\target.rs:160
  27:     0x7ff7244f99ec - exporter::take_screenshot
                               at W:\personal\ruffle\exporter\src\main.rs:142
  28:     0x7ff7244fba33 - exporter::capture_multiple_swfs
                               at W:\personal\ruffle\exporter\src\main.rs:292
  29:     0x7ff7244fd291 - exporter::main
                               at W:\personal\ruffle\exporter\src\main.rs:396
  30:     0x7ff72452204b - core::ops::function::FnOnce::call_once<fn() -> core::result::Result<tuple<>, alloc::boxed::Box<Error>>,tuple<>>
                               at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  31:     0x7ff72451bd5e - std::sys_common::backtrace::__rust_begin_short_backtrace<fn() -> core::result::Result<tuple<>, alloc::boxed::Box<Error>>,core::result::Result<tuple<>, alloc::boxed::Box<Error>>>
                               at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys_common\backtrace.rs:137
  32:     0x7ff724501b91 - std::rt::lang_start::{{closure}}<core::result::Result<tuple<>, alloc::boxed::Box<Error>>>
                               at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:66
  33:     0x7ff725b257d6 - core::ops::function::impls::{{impl}}::call_once
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\library\core\src\ops\function.rs:280
  34:     0x7ff725b257d6 - std::panicking::try::do_call
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:373
  35:     0x7ff725b257d6 - std::panicking::try
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:337
  36:     0x7ff725b257d6 - std::panic::catch_unwind
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panic.rs:379
  37:     0x7ff725b257d6 - std::rt::lang_start_internal
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\rt.rs:51
  38:     0x7ff724501b63 - std::rt::lang_start<core::result::Result<tuple<>, alloc::boxed::Box<Error>>>
                               at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:65
  39:     0x7ff7244fe3c0 - main
  40:     0x7ff725d98b34 - invoke_main
                               at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  41:     0x7ff725d98b34 - __scrt_common_main_seh
                               at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  42:     0x7ff9b32f7034 - BaseThreadInitThunk
  43:     0x7ff9b39bcec1 - RtlUserThreadStart
```

**Comment by cwfitzgerald** [comment]
So I took a look at this and it appears the code is hitting TDR and causing a device hang. There definitely might be a bug here, but this one isn't it, it's just manifesting in the same way. I'm going to close this issue for now, feel free to open a new one if you thing there's another issue.
