### ISSUE TITLE
Web examples do not work on Chrome canary 

### ISSUE THREAD

**Issue by trsh** [gfx-rs/wgpu#2157]
**Description**
Web examples do not work on Chrome canary. chrome://flags/#enable-unsafe-webgpu is On.

**Repro steps**
Open https://wgpu.rs/examples/?example=hello-triangle

**Expected vs observed behavior**

![err](https://user-images.githubusercontent.com/3727523/140619591-a93bc943-5400-46d5-a035-849c95fdb149.png)

**Platform**
Windows 10, 64bit, Nvidia GTX 750 Ti,

**Comment by grovesNL** [comment]
Hi @trsh! :wave: At the moment there are occasionally changes in the WebGPU specification which might temporarily break support for one of the browsers.

Until the specification stabilizes, we're focused on supporting Firefox Nightly first, so sometimes Chrome Canary might not work for some or all examples. The steps to running on Firefox Nightly are listed under https://github.com/gpuweb/gpuweb/wiki/Implementation-Status#firefox

**Comment by trsh** [comment]
It also doesn't work in FF nightly with the required flags enabled. Its just whit screen and this error:

```
Uncaught (in promise) Error: Using exceptions for control flow, don't mind me. This isn't actually an error!
    __wbindgen_throw https://wgpu.rs/examples/wasm/hello-triangle.js:861
    __wbg_adapter_49 https://wgpu.rs/examples/wasm/hello-triangle.js:250
    real https://wgpu.rs/examples/wasm/hello-triangle.js:199
    promise callback*init/imports.wbg.__wbg_then_2fcac196782070cc https://wgpu.rs/examples/wasm/hello-triangle.js:822
    __wbg_adapter_49 https://wgpu.rs/examples/wasm/hello-triangle.js:250
    real https://wgpu.rs/examples/wasm/hello-triangle.js:199
```

**Comment by trsh** [comment]
However other examples do work, except "shadow"

```

In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
In a set_bind_group command, caused by: bind group (12, 2, Vulkan) is invalid
command encoder is invalid
```

**Comment by sigmaxipi** [comment]
Adding some more data points.

The triangle example worked for me a moment ago but now I just get a blank white page and logs similar to https://github.com/gfx-rs/wgpu/issues/2157#issuecomment-962662702. Boids, Cube, Computer, Mipmap, and Skybox work consistently. Shadow fails with "In a set_bind_group command, caused by: bind group (15, 2, Vulkan) is invalid". This is on FF Nightly "96.0a1 (2021-11-08) (64-bit)".

(For the record, Chrome Canary "98.0.4695.2" only works with Cube and Compute at the moment)

On my local checkout (Sun Nov 7 13:47:02 746c938d19ea0abf65e5e19540ca9f611c42f4d5), `./run-wasm-example.sh hello-triangle` works on FF Nightly, but I'm having trouble with some of the other examples.

Win 10 + GTX 3090

**Comment by afiedler** [comment]
I think the Google Chrome team added a bunch of WebGPU validation in a recent release that is catching some rough edges in the WGPU implementation. I'm seeing this in Chrome Canary 98.0.4712.0:
![image](https://user-images.githubusercontent.com/466645/142504885-39cda655-5725-45cd-9118-1535c22b9ecd.png)

Looking at the history for `RenderPassEncoder.cpp`, you can see some validation added in recent commits:
https://dawn.googlesource.com/dawn/+log/2514566d8253e0d5839dba326ad15914b466699c/src/dawn_native/RenderPassEncoder.cpp

I'll look into this a little more to see what is going on.

**Comment by kvark** [comment]
Looks like we end up calling `set_index_buffer_with_f64_and_f64(.., .., .., 0)` sometimes, when instead we should be keeping it undefined.

**Comment by afiedler** [comment]
Right, this seems to fix it. Instead of using `.slice(..)` like this:
```rust
render_pass_encoder.set_vertex_buffer(0, mesh.vertex_buffer().slice(..));
render_pass_encoder.set_index_buffer(mesh.index_buffer().slice(..), wgpu::IndexFormat::Uint32);
```

You can provide the actual buffer sizes:
```rust
render_pass_encoder.set_vertex_buffer(0, mesh.vertex_buffer().slice(0..vbuf_size_in_bytes));
render_pass_encoder.set_index_buffer(mesh.index_buffer().slice(0..ibuf_size_in_bytes), wgpu::IndexFormat::Uint32);
```

But probably all/most of the methods in wgpu's `RenderInner` need to call the Javascript equivalents with `undefined` instead of just a default value.

**Comment by afiedler** [comment]
@kvark , I fixed this, at least for the methods I found to be broken in Chrome, here:
* https://github.com/afiedler/wgpu/commit/94c88f6a91eea5aa689789547ebd452dbeb13b0d
* https://github.com/afiedler/wgpu/commit/b97380fb8db0df7b8c1fea96d09162fef06dd704

Would you like a PR? If so, should this be fixed on `v0.11` or `master`?

**Comment by kvark** [comment]
Please make a PR for master. We don't consider it's worth trying to keep the past releases working in browsers, since the API is still not stable.

**Comment by afiedler** [comment]
@kvark , I created #2202

**Comment by cwfitzgerald** [comment]
This broke rend3 on the web, so it would be nice to get a patch out to v0.11. Normally I would just use wgpu master for the time being, but with 0.12 still a ways away, I can't hold up releases that long. 

Re web, I definitely doing think it's worth backporting major breaks, but small things like this that are fundamentally bugs, would be nice to fix.

**Comment by kvark** [comment]
There is a big list of things to back-port if you want to help with that :)
https://github.com/gfx-rs/wgpu/pulls?q=is%3Apr+is%3Aclosed+label%3A%22needs+back-porting%22
I'd be more than happy to publish. Just haven't seen enough calls to make those patch releases happen.

**Comment by cwfitzgerald** [comment]
Sure, I can do a backporting pass, get those all out in one swoop.
