### ISSUE TITLE
Validation Errors compute shaders - vkResetCommandPool, vkDestroyBuffer

### ISSUE THREAD

**Issue by peters-david** [gfx-rs/wgpu#2473]
I get a

0 took 5.152398114s
1 took 921.852867ms
MESA-INTEL: error: ../src/intel/vulkan/anv_device.c:3713: GPU hung on one of our command buffers (VK_ERROR_DEVICE_LOST)
thread 'main' panicked at 'Error in Queue::submit: parent device is lost', /home/david/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/6931e57/wgpu/src/backend/direct.rs:231:9

when running this code with "cargo run --release".

https://gist.github.com/peters-david/70a7a7ee6526cb35fe7f7b028cb820f5

Looks like the first two calls to `use_gpu()` work fine, after that it panics.
Is this intended? If so, why does it work the first two times?
If i remove the lazy_static and request a new `wgpu::Instance` in `use_gpu()` it works fine.

Sorry if this is a stupid question, just got started with Rust and wgpu.

I run it on a i7-1065G7 with the ICL GT2 on Linux Ubuntu 21.10.

**Comment by kvark** [comment]
Please check if you are using latest Intel drivers. We've been submitting issues lately, which are in different stages of fixing on Mesa side.

**Comment by kvark** [comment]
Also, please install Vulkan validation layers if you haven't already. I wonder if it spews out any useful info.

**Comment by peters-david** [comment]
In the private project i am getting the errors from above but the device isnt lost.
Instead im getting an output of all 0s, the same might be happening in #1881

**Comment by kvark** [comment]
Not exactly sure what is happening here, but it may very well be related that the tests we have are spewing errors as well when ran on multiple threads (from just `cargo test` on Linux). This is worrying, and we should fix this ASAP.

**Comment by peters-david** [comment]
Ok, let me know if you need anything more to reproduce / get additional information

**Comment by kvark** [comment]
Actually, the errors I was seeing are fixed by #2476, they are unrelated to your case. Moreover, we are running the compute test concurrently in `cargo test`, so it should be exercising similar paths. Is `cargo test` running well for you?

**Comment by peters-david** [comment]
On the ICL GT2 the tests seem to pass although im getting validation errors.
[icl_gt2.txt](https://github.com/gfx-rs/wgpu/files/8055033/icl_gt2.txt)

On the M4000 test conservative_raster fails.
[m4000.txt](https://github.com/gfx-rs/wgpu/files/8055035/m4000.txt)

**Comment by peters-david** [comment]
Your vk-astc branch shows all tests passed, no validation errors on ICL GT2.
On M4000 the conservative_raster still fails on vk-astc.

**Comment by kvark** [comment]
Ok, thank you for confirming! Would you be able to push your test case to a branch of wgpu somewhere, so that we can test it?

**Comment by peters-david** [comment]
Find it in https://github.com/peters-david/wgpu
The test is in wgpu/tests

**Comment by kvark** [comment]
Thanks @peters-david ! I ran your test on Intel Xe graphics (integrated).
First thing:
```
---- long_running_shader stdout ----
0
thread 'long_running_shader' panicked at 'assertion failed: `(left == right)`
  left: `100000`,
 right: `0`', wgpu/tests/long_running_shader.rs:120:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is due to a problem with your shader logic, which doesn't really set all the indices:
```rust
@builtin(global_invocation_id) id: vec3<u32>
@builtin(local_invocation_index) index: u32
var i: u32 = 256u*id.x+index;
```
For thread (1,0,0) within the only working group, we'll have `id.x == 1` and `index == 1`, so `i == 257`.

Once I fix this, the test just runs indefinitely (as you designed). No validation errors or warnings or asserts.

**Comment by peters-david** [comment]
The indexes don't start at 0??
