### ISSUE TITLE
Metal shader creation error: "attribute cannot be applied to types"

### ISSUE THREAD

**Issue by lisyarus** [gfx-rs/wgpu#4904]
I am using wgpu-native [from this build](https://github.com/gfx-rs/wgpu-native/actions/runs/7192422937), and running on MacOS. Pipeline creation fails with a weird error which sounds like a bug in WGSL -> Metal translation? Here's the error text:

```
thread '<unnamed>' panicked at src/lib.rs:389:5:
wgpu uncaptured error:
Validation Error

Caused by:
    In wgpuDeviceCreateRenderPipeline
      note: label = `env`
    Internal error in ShaderStages(FRAGMENT) shader: Metal: program_source:204:40: error: 'center_perspective' attribute cannot be applied to types
    metal::float2 vertex [[user(loc0), center_perspective]];
                                       ^
program_source:204:28: error: 'user' attribute cannot be applied to types
    metal::float2 vertex [[user(loc0), center_perspective]];
                           ^
program_source:204:5: warning: declaration does not declare anything
    metal::float2 vertex [[user(loc0), center_perspective]];
    ^~~~~~~~~~~~~
program_source:217:57: error: expected unqualified-id
    const EnvVertexOutput in_5 = { position, varyings_1.vertex };
                                                        ^
```

And here is the relevant shader code:

```

struct Camera {
    viewProjection : mat4x4f,
    viewProjectionInverse : mat4x4f,
    position : vec3f,
}

struct Lights {
    shadowProjection : mat4x4f,
    ambientLight : vec3f,
    sunDirection : vec3f,
    sunIntensity : vec3f,
    envIntensity : f32,
}

@group(0) @binding(0) var<uniform> camera: Camera;

@group(3) @binding(0) var<uniform> lights : Lights;
@group(3) @binding(1) var shadowSampler: sampler;
@group(3) @binding(2) var shadowMapTexture: texture_2d<f32>;
@group(3) @binding(3) var envSampler: sampler;
@group(3) @binding(4) var envMapTexture : texture_2d<f32>;

const PI = 3.141592653589793;

fn envDirectionToTexcoord(dir : vec3f) -> vec2f {
    let x = atan2(dir.z, dir.x) / PI * 0.5 + 0.5;
    let y = acos(dir.y) / PI;
    return vec2f(x, y);
}

fn sampleEnvMap(dir : vec3f) -> vec3f {
    // Help the GPU with mipmap selection
    // on cylindrical X coordinate border

    let texcoord1 = envDirectionToTexcoord(dir);
    let texcoord2 = vec2f(modf(texcoord1.x + 0.5).fract - 0.5, texcoord1.y);

    let sample1 = textureSample(envMapTexture, envSampler, texcoord1).rgb * lights.envIntensity;
    let sample2 = textureSample(envMapTexture, envSampler, texcoord2).rgb * lights.envIntensity;

    if (abs(texcoord1.x - 0.5) < 0.25) {
        return sample1;
    } else {
        return sample2;
    }
}

struct EnvVertexInput {
    @builtin(vertex_index) index : u32,
}

struct EnvVertexOutput {
    @builtin(position) position : vec4f,
    @location(0) vertex : vec2f,
}

@vertex
fn envVertexMain(in : EnvVertexInput) -> EnvVertexOutput {
    var vertex : vec2f;
    if (in.index == 0u) {
        vertex = vec2f(-1.0, -1.0);
    } else if (in.index == 1u) {
        vertex = vec2f( 3.0, -1.0);
    } else {
        vertex = vec2f(-1.0,  3.0);
    }

    return EnvVertexOutput(vec4f(vertex, 0.0, 1.0), vertex);
}

@fragment
fn envFragmentMain(in : EnvVertexOutput) -> @location(0) vec4f {
    let p0 = perspectiveDivide(camera.viewProjectionInverse * vec4f(in.vertex, 0.0, 1.0));
    let p1 = perspectiveDivide(camera.viewProjectionInverse * vec4f(in.vertex, 1.0, 1.0));
    let direction = normalize(p1 - p0);

    let sunCircle = smoothstep(0.9999, 0.99999, dot(direction, lights.sunDirection)) * lights.sunIntensity;

    return vec4f(tonemap(sampleEnvMap(direction) + sunCircle), 1.0);
}
```

**Comment by lisyarus** [comment]
Update: I can confirm that with wgpu-native version v22.1.0.5 the issue is fixed, thus I'm closing it.

**Comment by albert-yu** [comment]
I ran into a very similar error on wgpu 24.0. Turns out, it was because my `VertexOutput` had a conflicting name:

```wgsl
struct VertexOutput {
    @builtin(position) position: vec4f,
    @location(0) @interpolate(flat) instance: u32,
    @location(1) @interpolate(linear) vertex: vec2f,
};
```

Changing `vertex` to something else like `vertex_pos` fixed it.

```wgsl
struct VertexOutput {
    @builtin(position) position: vec4f,
    @location(0) @interpolate(flat) instance: u32,
    @location(1) @interpolate(linear) vertex_pos: vec2f,
};
```

For what it's worth, this was handled fine when running in Chromium.

**Comment by ErichDonGubler** [comment]
@albert-yu: This should be fixed in current Firefox Nightly builds, and the upcoming 25.* release series for native targets. Can you confirm the fix?

**Comment by albert-yu** [comment]
> [@albert-yu](https://github.com/albert-yu): This should be fixed in current Firefox Nightly builds, and the upcoming 25.* release series for native targets. Can you confirm the fix?

Thank you for following up, @ErichDonGubler!

Just tested with the nightly Firefox build `138.0a1 (2025-03-19) (aarch64)` by renaming the field back to `vertex`, but unfortunately I still get the error

```plain
Uncaptured WebGPU error: Internal error in ShaderStages(FRAGMENT) shader: Metal: program_source:133:28: error: 'user' attribute cannot be applied to types
    metal::float2 vertex [[user(loc1), center_no_perspective]];
                           ^
program_source:133:40: error: 'center_no_perspective' attribute cannot be applied to types
    metal::float2 vertex [[user(loc1), center_no_perspective]];
                                       ^
program_source:133:5: warning: declaration does not declare anything [-Wmissing-declarations
```

in the console. Re-applying the fix shows my program working as expected.

**Comment by ErichDonGubler** [comment]
Oh, sorry, I glossed over the fact that you're looking at a poorly handled _field name_, not a structure name. I've filed a separate issue at <https://github.com/gfx-rs/wgpu/issues/7378>, since that's another case that needs to be handled.

**Comment by lisyarus** [comment]
I'm afraid the issue is still present. I'm using wgpu-native v29.0.1.1 this time, and I get a similar problem caused by a struct field called `vertex`. Specifically, compiling this shader

```wgsl
struct VertexOut
{
	@builtin(position) position : vec4f,
	@location(0) vertex : vec2f,
}

@vertex
fn vertex_main(@builtin(vertex_index) index : u32) -> VertexOut
{
	let vertex = vec2f(0.0);

	return VertexOut(
		vec4f(vertex, 0.0, 1.0),
		vertex
	);
}

@fragment
fn fragment_main(in : VertexOut) -> @location(0) vec4f
{
	return vec4f(1.0);
}
```

I get the error

```
WebGPU: Shader translation error for stage ShaderStages(FRAGMENT): Metal: program_source:14:28: error: 'user' attribute cannot be applied to types
    metal::float2 vertex [[user(loc0), center_perspective]];
                           ^
program_source:14:40: error: 'center_perspective' attribute cannot be applied to types
    metal::float2 vertex [[user(loc0), center_perspective]];
                                       ^
program_source:14:5: warning: declaration does not declare anything [-Wmissing-declarations]
    metal::float2 vertex [[user(loc0), center_perspective]];
    ^~~~~~~~~~~~~
program_source:23:47: error: expected unqualified-id
    const VertexOut in = { position, varyings.vertex };
                                              ^

WebGPU: Please report it to https://github.com/gfx-rs/wgpu

Uncaptured WebGPU error, type: 2, message: Validation Error

Caused by:
  In wgpuDeviceCreateRenderPipeline, label = 'underwater'
    Internal error in ShaderStages(FRAGMENT) shader: Metal: program_source:14:28: error: 'user' attribute cannot be applied to types
    metal::float2 vertex [[user(loc0), center_perspective]];
                           ^
program_source:14:40: error: 'center_perspective' attribute cannot be applied to types
    metal::float2 vertex [[user(loc0), center_perspective]];
                                       ^
program_source:14:5: warning: declaration does not declare anything [-Wmissing-declarations]
    metal::float2 vertex [[user(loc0), center_perspective]];
    ^~~~~~~~~~~~~
program_source:23:47: error: expected unqualified-id
    const VertexOut in = { position, varyings.vertex };
                                              ^
```

Renaming the `vertex` field to something else fixes the error.

**Comment by ErichDonGubler** [comment]
@lisyarus: Can you please reproduce with latest wgpu? Note that wgpu-native tends to lag behind in the version of wgpu it consumes.

EDIT: Closing (again) for now. I'm not persuaded this is actually still a problem, but will re-open with a repro.
