### ISSUE TITLE
Panic trying to allocate 2049th bind group on DX12

### ISSUE THREAD

**Issue by Dinnerbone** [gfx-rs/wgpu#954]
**Description**
After allocating around 2028 bind groups that contain a sampler, the next call will panic dx12 in the following way:
```
[0.946133 INFO](Device::create_bind_group)(no module): create_descriptor_pool with 512 max sets
[0.946152 INFO](Device::create_bind_group)(no module): total 0 views and 512 samplers
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RangeAllocationError { fragmented_free_length: 0 }', C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.6.2\src\device.rs:2867:22
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\fmt\mod.rs:1069
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\io\mod.rs:1504
   5: std::sys_common::backtrace::_print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:511
  10: std::panicking::begin_panic_handler
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:419
  11: core::panicking::panic_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\panicking.rs:111
  12: core::option::expect_none_failed
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\option.rs:1268
  13: core::result::Result<core::ops::range::Range<u64>, range_alloc::RangeAllocationError<u64>>::unwrap<core::ops::range::Range<u64>,range_alloc::RangeAllocationError<u64>>
             at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\result.rs:1005
  14: gfx_backend_dx12::device::{{impl}}::create_descriptor_pool<arrayvec::ArrayVec<[gfx_hal::pso::descriptor::DescriptorRangeDesc; 15]>>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.6.2\src\device.rs:2867
  15: gfx_descriptor::allocator::DescriptorBucket<gfx_backend_dx12::Backend>::allocate<gfx_backend_dx12::Backend>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-descriptor-0.2.0\src\allocator.rs:178
  16: gfx_descriptor::allocator::DescriptorAllocator<gfx_backend_dx12::Backend>::allocate<gfx_backend_dx12::Backend,arrayvec::ArrayVec<[gfx_descriptor::allocator::DescriptorSet<gfx_backend_dx12::Backend>; 1]>>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-descriptor-0.2.0\src\allocator.rs:296
  17: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_bind_group<wgpu_core::hub::IdentityManagerFactory,gfx_backend_dx12::Backend>
             at C:\Users\dinne\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\43adcbc\wgpu-core\src\device\mod.rs:1949
  18: wgpu::backend::direct::{{impl}}::device_create_bind_group
             at .\src\backend\direct.rs:712
  19: wgpu::Device::create_bind_group
             at .\src\lib.rs:1471
  20: hello_triangle::run::{{closure}}
             at .\examples\hello-triangle\main.rs:47
```

This does not seem to happen on DX11 or Vulkan, and I can't reproduce it without a sampler (though I haven't investigated every type of binding).

**Repro steps**
The following code is the smallest test case I can reproduce with.

```rust
async fn run() {
    let instance = wgpu::Instance::new(wgpu::BackendBit::DX12);
    let adapter = instance.request_adapter(&Default::default()).await.unwrap();
    let (device, _) = adapter.request_device(&Default::default(), None).await.unwrap();

    let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
        label: None,
        entries: &[wgpu::BindGroupLayoutEntry {
            binding: 0,
            visibility: wgpu::ShaderStage::FRAGMENT,
            ty: wgpu::BindingType::Sampler { comparison: false },
            count: None,
        }],
    });

    let sampler = device.create_sampler(&Default::default());

    for i in 0..3000 {
        println!("Call #{}", i + 1);
        device.create_bind_group(&wgpu::BindGroupDescriptor {
            layout: &bind_group_layout,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: wgpu::BindingResource::Sampler(&sampler),
            }],
            label: None,
        });
    }
}

fn main() {
    futures::executor::block_on(run());
}
```

**Expected vs observed behavior**
I expect it to not panic.

**Extra materials**
N/A

**Platform**
OS: Windows 10
Backend: DirectX 12
WGPU: I've tested with wgpu-rs 0.6.0 and `0609e95ed7335e3abe1663943d6e04f640d24acb` (latest master at current)

**Comment by kvark** [comment]
Ah I see. This is a limitation of DX12 specifically: it doesn't allow more than 2048 samplers in a single heap.
I'm working on a crazy-ish solution in https://github.com/gfx-rs/gfx/pull/3393

**Comment by kvark** [comment]
As a workaround, just use less bind groups containing samplers in general. I.e. if you have bind group 0 for per-frame data, 1 for per material, and 2 - for per object, then try to have all the samplers in group 0.

**Comment by kvark** [comment]
This is now mostly resolved in gfx-backend-dx12-0.6.6

**Comment by AlienSmith** [comment]
Hello there, we run into the same error the other day. Besides, We can still reproduce the same error in your mipmap example by creating 2049 bindgroups with sampler at init. Please help us.

**Comment by cwfitzgerald** [comment]
The issue you're hitting is #3350 - it can be worked around by splitting out samplers into their own bind groups nad having as few sampler bind groups at possible, such that there are no more than 2032 total bindings alive.
